services:
  db:
    image: mysql:8.0
    container_name: kljobs_db_container
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=512M
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kljobs_db
      MYSQL_USER: kljobs_user
      MYSQL_PASSWORD: PX#lGJi5D68lH@
    ports:
      - "3306:3306"  # Exposed to Host:3306 for Vercel connection
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: kljobs_redis
    restart: always
    ports:
      - "6379:6379"

  job-scraper:
    build: .
    container_name: job-scraper
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=kljobs_user
      - DB_PASSWORD=PX#lGJi5D68lH@
      - DB_NAME=kljobs_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SCRAPE_INTERVAL=43200
      - INFOPARK_URL=https://infopark.in/companies/job-search
      - TECHNOPARK_URL=https://technopark.org/api/paginated-jobs
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENROUTER_API_KEYS=${OPENROUTER_API_KEYS}
      - SCRAPE_INTERVAL=43200
      - PROCESS_INTERVAL=3600
      - OR_KEY_RPM_LIMIT=20
      - OR_KEY_DAILY_LIMIT=50
    volumes:
      - ./scraping_config.json:/app/scraping_config.json

volumes:
  db_data:
